services:
  redmine:
    image: redmine:latest
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
      SECRET_KEY_BASE: supersecretkey
      TZ: Asia/Yekaterinburg
    command: >
      bash -lc "cd /usr/src/redmine &&
      bundle install --without development test &&
      bundle exec rake generate_secret_token RAILS_ENV=production &&
      bundle exec rake db:migrate RAILS_ENV=production &&
      bundle exec rake redmine:plugins:migrate RAILS_ENV=production &&
      bundle exec rails server -b 0.0.0.0 -p 3000 -e production"
    volumes:
      - ./themes:/usr/src/redmine/public/themes
      - ./themes:/usr/src/redmine/themes
      - ./plugins:/usr/src/redmine/plugins
      - ./redmine_files:/usr/src/redmine/files
      - ./config/database.yml:/usr/src/redmine/config/database.yml

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
